---
title: "ALS"
author: "Chen Guo-Bo [chenguobo@gmail.com]"
date: "`r Sys.Date()`"
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

```{r setup, echo=FALSE}
#knitr::opts_chunk$set(echo = TRUE)
library(pROC)
library("knitr")
library("kableExtra")

dat=read.csv("./data/20200818all_bmi.csv", as.is = T, header = T)

```

# Table of contents {.tabset .tabset-fade .tabset-pills}

## Quality check
```{r, data-check}

par(las=2, font=5, bty='l', ps=6)
boxplot(dat[,-2], cex=0.5, pch=16, col=runif(nrow(dat), 1, nrow(dat)))

##basic accessment of the data
###fivenum, mean, sd, missing, isNumeric
cutoff=7 #outlier pickup

SUMmat=matrix(0, ncol(dat), 10)
colnames(SUMmat)=c("minimum", "lower-hinge", "median", "upper-hinge", "maximum", "mean", "sd", "missingRate", "isNumeric", "CaseOnly")
rownames(SUMmat)=colnames(dat)
for(i in 1:nrow(SUMmat)) {
  if(is.numeric(dat[,i])) {
    SUMmat[i,1:5]=fivenum(dat[,i])
    SUMmat[i,6]=mean(dat[,i], na.rm = T)
    SUMmat[i,7]=sd(dat[,i], na.rm = T)
    naIdx=which(!is.na(dat[,i]))
    SUMmat[i,8]=1-length(naIdx)/nrow(dat)
    SUMmat[i,9]=T
    SUMmat[i,10]=ifelse(length(unique(dat[naIdx,1]))==1, T, F)

    idx=which(dat[,i] > SUMmat[i,6]+cutoff*SUMmat[i,7])
    if(length(idx)>0) {
      for(j in 1:length(idx)) {
        print(paste0("sample id: ",dat[idx[j],2], ", col:", colnames(dat)[i], ", ", "outlier value: ",  dat[idx[j], i]))
      }

    }
  } else {
    SUMmat[i,1:8]=NA
    SUMmat[i,9]=F
  }
}

write.table(SUMmat, "Als_sumDat.txt", row.names = T, col.names = T, quote = F)

#basicSum=read.table("Als_sumDat.txt", as.is = T, header = T)

#knitr::kable(basicSum, caption = "Data quality") %>%
knitr::kable(SUMmat, caption = "Data quality") %>%

kable_styling("striped", full_width = T)
#row_spec(row=16:16, color="white", background="red")

```


## Baseline characteristics

```{r, Baseline}
datMat=matrix(0, 4, 5)
colnames(datMat)=c("sex", "age", "height", "weight", "BMI")
rownames(datMat)=c("Cs mean", "Cs sd", "Ctrl mean", "Ctrl sd")
datCs=as.matrix(dat)[dat$casectrl==1,c("sex", "age", "height", "weight", "BMI")]

datMat[1,]=apply(datCs, 2, mean)
datMat[2,]=apply(datCs, 2, sd)

datCtrl=as.matrix(dat)[dat$casectrl==0,c("sex", "age", "height", "weight", "BMI")]
idxCtrlBMI=which(is.na(datCtrl[,"BMI"]))
datCtrl[idxCtrlBMI, c("BMI")]=datCtrl[idxCtrlBMI, "weight"]/datCtrl[idxCtrlBMI, "height"]^2

datMat[3,]=apply(datCtrl[,], 2, mean)
datMat[4,]=apply(datCtrl[,], 2, sd)

knitr::kable(datMat, caption="Demographic") %>%
kable_styling("striped", full_width = T) %>%
row_spec(row=3:4, color="white", background="red")

knitr::kable(SUMmat[SUMmat[,ncol(SUMmat)]==1, c(1,3,5,6,7)], caption = "Baseline characteristics") %>%
kable_styling("striped", full_width = T)
#row_spec(row=16:16, color="white", background="red")

```


## Feature selection
```{r, data-p}
Smat=matrix(0, ncol(dat)-2, 4)

for(i in 3:ncol(dat)) {
  mod=glm(dat[,1]~dat[,i], family = "binomial")
  Smat[i-2,]=summary(mod)$coefficients[2,]
}
rownames(Smat)=colnames(dat)[3:ncol(dat)]


aucMat=matrix(2, ncol(dat)-2, 1)
rownames(aucMat)=colnames(dat)[3:ncol(dat)]
for(i in 3:ncol(dat)) {
  if(!SUMmat[colnames(dat)[i],10]) {
    rocObj=roc(dat[,1], dat[,i], quiet = T)
    aucMat[i-2,1]=rocObj$auc
  }
}

layout(matrix(c(1, 2, 3, 4), 2, 2, byrow = F))
par(las=2, cex=0.5, mai=c(1,0.5,0.5,0.5))
pcut=-log10(0.05/(ncol(dat)-2))
barplot(main="case-control",-log10(Smat[,4]), col=ifelse(-log10(Smat[,4])>pcut, "cyan", "grey"))
abline(h=-log10(0.05/ncol(dat)), col="red", lty=2)

barplot(main="case-control", aucMat, beside = T, col=ifelse(-log10(Smat[,4])>pcut, "cyan", "grey"))
plot(-log10(Smat[,4]), pch=16,aucMat,col=ifelse(-log10(Smat[,4])>pcut, "cyan", "grey"))
abline(v=pcut, col="red", lty=2)

###########
SVCmat=matrix(1, ncol(dat)-2, 4)
for(i in 3:ncol(dat)) {
  if(i!=68) {
    mod=lm(dat[,68]~dat[,i])
    if(nrow(summary(mod)$coefficients)>1) {
      SVCmat[i-2,]=summary(mod)$coefficients[2,]
    }
  }
}
rownames(SVCmat)=colnames(dat)[3:ncol(dat)]
colnames(SVCmat)=c("est", "se", "t", "-log10(p)")
SVCmat[,4]=-log10(Smat[,4])
par(las=2, cex=0.5, mai=c(1.5,0.5,0.5,0.5))
pcut=-log10(0.05/(ncol(dat)-2))
barplot(SVCmat[,4], col=ifelse(SVCmat[,4]>pcut, "cyan", "grey"))
abline(h=-log10(0.05/ncol(dat)), col="red", lty=2)

knitr::kable(SVCmat, caption = "Feature") %>%
kable_styling("striped", full_width = T) %>%
row_spec(row=which(SVCmat[,4]>pcut), color="white", background="red")

```

## REEp
Resting energy expenditure
```{r, Reep}
layout(matrix(1:3, 1, 3))
hist(dat[,"REEp"], breaks = 25, main="All", xlab="REEp")
hist(dat[which(dat$casectrl==0), "REEp"], breaks=25, main="control", xlab="REEp")
hist(dat[which(dat$casectrl==1), "REEp"], breaks=25, main="case", xlab="REEp")

Th=c(1.0, 1.1, 1.2, 1.3, 1.35, 1.4, 1.45, 1.5)
propREE=matrix(1:6, 2, length(Th))
colnames(propREE)=Th
rownames(propREE)=c("ctrl", "cs")
for(i in 1:length(Th)) {
  propREE[1,i]=length(which(dat[(dat$casectrl==0), "REEp"]>Th[i]))/nrow(dat[dat$casectrl==0,])
  propREE[2,i]=length(which(dat[(dat$casectrl==1), "REEp"]>Th[i]))/nrow(dat[dat$casectrl==1,])
}
#print(propREE)
layout(matrix(1:1, 1, 1))
barplot(propREE, beside = T, border = F)
abline(h=c(0.5, 0.55, 0.6), lty=2, col="red")
legend("topright", legend = c("Ctrl", "Cs"), col = c("black", "grey"), pch=16)
```

